from . import sage_binding
from . import sage_backend
from . import res_partner
from . import hr_employee
from . import payroll_sage_labour_agreement
from . import payroll_sage_labour_agreement_wage_type_line
from . import payroll_sage_payslip_line
from . import payroll_sage_payslip_line_payroll
from . import payroll_sage_payslip_line_transfer
from . import payroll_sage_payslip_check
from . import payroll_sage_payslip
