from . import binding
from . import backend
from . import res_partner
from . import product_product
from . import sale_order
from . import sale_order_line
from . import spms_lot
from . import spms_prescription_type
from . import spms_context
from . import spms_suspension_reason
