from . import backend
from . import binding
from . import common
from . import product_public_category
from . import product_attribute
from . import product_attribute_value
from . import product
from . import product_template
from . import product_product
from . import res_partner
from . import sale_order_line
from . import sale_order
from . import stock_picking
