from . import oxigesti_binding
from . import oxigesti_backend
from . import res_partner
from . import product_template
from . import product_product
from . import product_category
from . import product_buyerinfo
from . import product_pricelist_item
from . import stock_production_lot
from . import sale_order_line
from . import sale_order
from . import account_invoice
