from . import ir_attachment
from . import mail_activity
from . import mail_mail
from . import mail_message
from . import mail_thread
from . import project_project
from . import project_task
from . import project_task_recurrence
from . import project_task_stage_personal
from . import rating_rating
from . import res_groups
from . import res_users
